import constants from 'namespace-constants';

export const {
    MODAL_WATCH_DIRECTORY,
    NOTIFICATION_CATEGORY_PROGRAM_PAUSE,
    NOTIFICATION_CATEGORY_PROGRAM_END,
    NOTIFICATION_CATEGORY_TOOL_CHANGE
} = constants('widgets/Visualizer', [
    'MODAL_WATCH_DIRECTORY',
    'NOTIFICATION_CATEGORY_PROGRAM_PAUSE',
    'NOTIFICATION_CATEGORY_PROGRAM_END',
    'NOTIFICATION_CATEGORY_TOOL_CHANGE'
]);

export const CAMERA_MODE_PAN = 'pan';
export const CAMERA_MODE_ROTATE = 'rotate';

