module.exports = [
    { type: 'header', text: 'Wait for the planner queue to empty' },
    '%wait\n',
    { type: 'header', text: 'Keep current work position' },
    '%_x0=posx,_y0=posy,_z0=posz\n',
    { type: 'header', text: 'Move to the saved work position' },
    'G0 X[_x0] Y[_y0]',
    { type: 'header', text: 'Keep current modal groups' },
    '%_wcs=modal.wcs\n',
    '%_plane=modal.plane\n',
    '%_units=modal.units\n',
    '%_distance=modal.distance\n',
    '%_feedrate=modal.feedrate\n',
    '%_spindle=modal.spindle\n',
    '%_coolant=modal.coolant\n',
    { type: 'header', text: 'Restore to previous modal groups' },
    '[_wcs] [_plane] [_units] [_distance] [_spindle] [_coolant]\n',
    { type: 'header', text: 'Set bounding box' },
    '%xmin=0,xmax=100,ymin=0,ymax=100\n',
    { type: 'header', text: 'Work position' },
    '[posx]',
    '[posy]',
    '[posz]',
    '[posa]',
    { type: 'header', text: 'Bounding box' },
    '[xmin]',
    '[xmax]',
    '[ymin]',
    '[ymax]',
    '[zmin]',
    '[zmax]'
];
