const variables = [
  { type: 'header', text: 'Tool Change and Probe Variables' },
  '[tool_change_x]',
  '[tool_change_y]',
  '[tool_change_z]',
  '[tool_probe_x]',
  '[tool_probe_y]',
  '[tool_probe_z]',
  '[tool_probe_command]',
  '[tool_probe_distance]',
  '[tool_probe_feedrate]',
  '[touch_plate_height]',
  { type: 'header', text: 'Machine Position' },
  '[mposx]',
  '[mposy]',
  '[mposz]',
  { type: 'header', text: 'Work Position' },
  '[posx]',
  '[posy]',
  '[posz]',
  { type: 'header', text: 'Bounding Box' },
  '[xmin]',
  '[xmax]',
  '[ymin]',
  '[ymax]',
  '[zmin]',
  '[zmax]',
];

export default variables;
